#include<iostream>
using namespace std;
/*
    why virtual base class be used?
        to solve ambiguity generated by hierarchical and multiple inheritance.
    
              B----------->
    A--------->             >>>>>>>>D
              C----------->
              
    if A has a member or method and it is inheritable then D will get that member and method two times .

            To solve this ambiguity we make A as virtual base class.
            syntax for virtual base class
                    class B : virtual public C{

                    };

*/
int main(){
    
return 0;
}